from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .smart_image_size_resize import (
    NODE_CLASS_MAPPINGS as RESIZE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_minimum_1k import (
    NODE_CLASS_MAPPINGS as MINIMUM_1K_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MINIMUM_1K_NODE_DISPLAY_NAME_MAPPINGS,
)
from .video_frames_workflow import (
    NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS.update(RESIZE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RESIZE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MINIMUM_1K_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MINIMUM_1K_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NODE_DISPLAY_NAME_MAPPINGS)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
