from .smart_image_size import (
    NODE_CLASS_MAPPINGS as SIZE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SIZE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .smart_image_resize import (
    NODE_CLASS_MAPPINGS as RESIZE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .image_minimum_1k import (
    NODE_CLASS_MAPPINGS as MINIMUM_1K_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MINIMUM_1K_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(SIZE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SIZE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RESIZE_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RESIZE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MINIMUM_1K_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MINIMUM_1K_NODE_DISPLAY_NAME_MAPPINGS)


__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
